# Project Information
site_name: 道品空间
site_description: 道品空间
site_author: 道品空间
site_url: https://daopinkongjian.github.io
site_dir: site
docs_dir: docs
copyright: '道品空间 版权所有 Copyright © 2020-2025 daopinkongjian All Rights Reserved.'

# Contents 导航
nav:
  - 首页: 
    - 念住禅项目简介: index.md
  - 念住项目活动: activity.md
  - 义脉树枝图生成器: tools/yimaishuzhitu.html

# Theme 主题设置
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand
  language: 'zh'
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'
  palette:
      # Toggle light mode
      - scheme: default
        primary: white
        accent: red
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Toggle dark mode
      - scheme: slate
        primary: black
        accent: teal
        toggle:
          icon: material/weather-night
          name: Switch to light mode